openapi: 3.0.0

info:
  title: Customer Directory API
  version: 1.0.0
  description: Customer mock API hosted on Beeceptor

servers:
  - url: https://rest-demo.free.beeceptor.com

paths:

  /customers:
    get:
      operationId: getCustomers
      summary: Get all customers
      description: Returns all customers.
      responses:
        '200':
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'

  /customers/{customerId}:
    get:
      operationId: getCustomerById
      summary: Get customer by ID
      description: Returns a specific customer.
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          example: CUST-1001
      responses:
        '200':
          description: Customer found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found

components:

  schemas:

    Customer:
      type: object
      required:
        - CustomerID
        - FullName
        - EmailAddress
        - Country
        - AccountStatus

      properties:

        CustomerID:
          type: string
          example: CUST-1001

        FullName:
          type: string
          example: Michal Cohen

        EmailAddress:
          type: string
          format: email
          example: michal.cohen@startup.net

        PhoneNumber:
          type: string
          example: "+972-54-3504657"

        Country:
          type: string
          example: Canada

        AccountStatus:
          type: string
          enum:
            - Active
            - Inactive
            - Pending
            - Suspended
          example: Inactive

        SignupDate:
          type: string
          format: date
          example: "2026-01-27"
